version: "3.9"
services:
  api:
    build: ./backend
    container_name: anti-scam-api
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    container_name: anti-scam-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/seed:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: anti-scam-redis
    ports: ["6379:6379"]

volumes:
  pgdata:
